modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://example.com/${mod_id}"
logoFile="${mod_id}.png"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
